[server]
maxUploadSize = 1024
enableXsrfProtection = true
enableCORS = true

[browser]
gatherUsageStats = false

[theme]
primaryColor = "#c1d100"
backgroundColor = "#2b2825"
secondaryBackgroundColor = "#1e342e"
textColor = "#f7f1e3"
font = "sans serif"
